### ISSUE TITLE
Provide way to access status code in global error handler

### ISSUE THREAD

**Issue by adstage-david** [untangled-web/client#14]
Now that we're on the latest release, (:networking app) doesn't allow direct access to the xhr-io object, so we can't use the error handler we had set up before. This would be fine since network_error_callback is available now, but the network_error_callback gets back only the body of the error, not the status code (and status code might be useful in some circumstances). Either the status code should be passed into the network_error_callback, or we'll need some way to access the xhr-io object to get the status code ourselves to keep our error callback working.

**Comment by awkay** [comment]
@mahinshaw made this change during the generalization for the websockets lib...I'll see if I can get him to look at it. The point is that the xhr-io object might not be there, since using websockets obviates the need for it. That also means a status code is not always available, depending on the network layer (except on initial connection)

**Comment by adstage-david** [comment]
Maybe a good fix if we need this is just to make sure error handler on the server side returns the status code in the response message so that it's transport layer independent?

**Comment by mahinshaw** [comment]
The most reasonable fix for this is passing the status code to the global error handler (ex '(fn [status body] do stuff with parens))'. Websockets get the status gose returned as well so the behavior would be analogous. This will be an api change, but an easy and non intrusive one. If we want to do this I can make a patch for both client and Websockets.

**Comment by awkay** [comment]
Sounds good to me. Thanks!

**Comment by mahinshaw** [comment]
@adstage-david I added facilities for getting the status through the `global-error-callback`.  Now when you pass a global error callback you will need to define an arity 2 function like `(defn err [status body] (println status))`.  The code is on develop.  Let me know if that is sufficient for you.

**Comment by awkay** [comment]
um, @mahinshaw , that sounds like it changes the API? Status should be added as a new parameter, and should never bump a parameter order....oh, wait, did the original not take anything?
