### ISSUE TITLE
App with union query does not appear to work on 0.5.3 + advanced optimizations

### ISSUE THREAD

**Issue by adstage-david** [untangled-web/client#21]
Tracing back an error after bumping to 0.5.3, I come back to here: https://github.com/untangled-web/untangled-client/blob/master/src/untangled/client/core.cljs#L227

Seems like it should be fine, but when turning on advanced compilation, it stops working. After a bit of time investigating how protocols and om.next's static version of them works, I believe that it is not valid to call `om/ident` directly if you want advanced compilations to work - see how `om/get-query` works for `om/IQuery` ( a very similar case to the `om/Ident` protocol):

https://github.com/omcljs/om/blob/747655fe65b4a46a502d9b76171642ef0f67d532/src/main/om/next.cljs#L302-L309

**Comment by awkay** [comment]
Argh. Nice find. Not surprising that the "made up" support for static in Om is tricky.

**Comment by awkay** [comment]
I copied the technique into the relevant area. I don't have time to test the advanced compilation, but it doesn't seem to break anything in normal. Could you try out 0.5.5-SNAPSHOT and see if it is better? I just pushed to clojars

**Comment by adstage-david** [comment]
Sorry, this comment got lost in my inbox - yes, 0.5.5-SNAPSHOT appears to work fine for this case

**Comment by awkay** [comment]
I think the latest versions of Om and the cljs compiler generally fix these. We should re-test them and close this if they work.

The workaround code I added should probably also be removed from client core.

**Comment by awkay** [comment]
Jason Jackson reports advanced optimizations are working better with latest versions of Om/Untangled. Please try again.
