### ISSUE TITLE
Application#started-callback should be called after initial-state generation

### ISSUE THREAD

**Issue by borovsky** [untangled-web/client#23]
Now started-callback called just after application creation, but union expansion done after mounting application.

As result it's impossible to use started-callback for additional initialization, e.g. initial routing.

**Comment by awkay** [comment]
Ah, well, if that's the case you are correct...we should correct that. If you wanted to send a PR, great; otherwise we'll get to it soon I hope.

**Comment by awkay** [comment]
This is fixed and deployed to clojars in 0.5.5-SNAPSHOT
