### ISSUE TITLE
:ui/fetch-state is not set for queries with params

### ISSUE THREAD

**Issue by mitchelkuijpers** [untangled-web/client#32]
I have a repository where I could very easily reproduce the issue:

https://github.com/mitchelkuijpers/untangled-template-workspace/blob/master/src/client/template/ui/main.cljs#L42

**Comment by awkay** [comment]
Thanks, I'll have a look. Not sure when I can get to it.

If you wanted to have a look yourself, the code that places load markers is on line 31 of .../impl/data_fetch.cljs `place-load-markers`

**Comment by awkay** [comment]
Note: Your code is setting marker to false, which means it should never set a fetch state marker there.

**Comment by awkay** [comment]
More likely line 335 (in the `error-callback` remove-markers). That is placing error markers without checking to see if it is supposed to...so that actually is a bug.

**Comment by mitchelkuijpers** [comment]
Yeah I also noted the `marker: false` I think I looked at the problem a bit too long. But it seems to still place the marker, as you noted.

**Comment by mitchelkuijpers** [comment]
Seems related to #24 #22

**Comment by egracer** [comment]
@awkay I am patching this as we speak. Confirmed with @mitchelkuijpers that #22 and this issue are resolved with the same patch.

**Comment by awkay** [comment]
@egracer Nice. Thanks!
