### ISSUE TITLE
Union queries with InitialAppState seem to break normalization with 0.5.8-SNAPSHOT

### ISSUE THREAD

**Issue by mitchelkuijpers** [untangled-web/client#44]
I changed nothing between 0.5.7 and 0.5.8-SNAPSHOT (added it to have the devcards niceness with atoms and displaying them) And I noticed some of the views with unions and initial-state stopped working. I cannot share the complete code but this is basically what is happening in the app-state:

0.5.7

```
{:entity/current-tab [:ui.entities.current-view/overview 0],
```

0.5.8-SNAPSHOT

```
{:entity/current-tab {0 :ui.entities.current-view/overview},
```

**Comment by mitchelkuijpers** [comment]
I just tested the "Tabbed Interfaces" cookbook recipe  and there I notice the same behaviour so it is very easily reproducible:

```
 :current-tab {0 :main}
```

The only thing I did was upgrade to `0.5.8-SNAPSHOT`, and I updated om to `1.0.0-alpha46`

https://github.com/untangled-web/untangled-cookbook/tree/master/recipes/tabbed-interface

**Comment by awkay** [comment]
That is really strange...I'll look into it. Thanks for the report.

**Comment by awkay** [comment]
Fixed on develop, SNAPSHOT pushed to clojars.
