### ISSUE TITLE
app state passed to global error callback does not have the `:untangled/server-error` in that app state.

### ISSUE THREAD

**Issue by mahinshaw** [untangled-web/client#59]
When hooking into the global error callback, there are two parameters passed in, the app-state, and the error/status code returned from the server.  It would be nice to have access to the most recent changes to the app state with regard to server errors.  The modification would involve reordering the calls to the `global-error-callback` and the `error-callback seen` here:

https://github.com/untangled-web/untangled-client/blob/develop/src/untangled/client/impl/network.cljc#L63

the `error-callback` is the function that does the insertion of the `:untangled/server-error` which is implemented here:

https://github.com/untangled-web/untangled-client/blob/develop/src/untangled/client/impl/data_fetch.cljc#L409

Any issues with reordering these two calls?

**Comment by awkay** [comment]
Hm. Kind of a potentially breaking change. The error-callback is what triggers fallbacks, so if someone was expecting global handling results in the fallback, then their (possibly existing) error handling might break.

The global handler is generally only meant for catastrophic failures that you cannot reasonable recover from, so you don't have to code them in every transact as fallbacks. What are you wanting to do in your application that could deal with it?

**Comment by mahinshaw** [comment]
If that's the case, we need to update this document: 

https://github.com/untangled-web/untangled-cookbook/blob/master/recipes/error-handling/README.md

It implies that the marker is set, and the global error callback can use that marker to dispatch.

**Comment by awkay** [comment]
Ah, well, in that case I'd consider it a bug, and say that reordering the statements is the right thing to do.
