### ISSUE TITLE
Allow custom reconciler options

### ISSUE THREAD

**Issue by wilkerlucio** [untangled-web/client#63]
Currently Untangled restricts which reconciler options can be sent for the Om reconciler. While I understand the desire to prevent users from doing bad things, his limitation made for a while be impossible to use `shared`, that now is added. I'm trying to develop a React Native app with Untangled, and then I got stuck into the reconciler options again, this time I need to send `:root-render` and `:root-unmount` to be able to render in React Native.

I propose we add a `:reconciler-options` to `new-untangled-client`, which should be a map that will be merged into the reconciler options, this way we fix the issue and any future issues regarding possible changes on reconciler for the future.

**Comment by awkay** [comment]
Sure, just needs to do the right thing with respect to the options we're
hooked into.
 Love to see native working.
