### ISSUE TITLE
Load marker stomps on data if it's a not normalized map

### ISSUE THREAD

**Issue by Pancia** [untangled-web/client#70]
```
{:todos {:list/title "main",
         :list/items [],
         :list/filter :list.filter/completed}}
```
TodoItem query => `[:db/id :item/label]`
TodoList query => `[:db/id :list/title :list/filter {:list/items TodoItem}]`

`(df/load :todos TodoList {:params {:list "main"}}`

Results in `:todos` being wiped so that `:list/filter` does not exist after the load merge.

**Comment by awkay** [comment]
Pretty sure this is fixed in 0.8.1-SNAPSHOT by commit 70902
