### ISSUE TITLE
Better Error with untangled.client.impl.om-plumbing/not-found

### ISSUE THREAD

**Issue by adstage-david** [untangled-web/client#9]
I'm trying to debug an error we sometimes in our app:

Uncaught Error: No protocol method IWithMeta.-with-meta defined for type cljs.core/Keyword: :untangled.client.impl.om-plumbing/not-found

More information here might be helpful in debugging the message. Apparently likely culprits are client queries trying to access properties no longer available on the server, or a client trying to make a query with tempids.

**Comment by awkay** [comment]
If you can give me a reproducible case I could possibly fix this. I'd need to see where the error is occurring. It might be something I can pre-filter, or at least catch and report.

**Comment by adstage-david** [comment]
I can't remember in what scenario this happened or how to reproduce it, but if I do see it again I'll try to reduce it to a reproducible case and reopen here. Probably was just some other bug in our code we fixed.
